### ISSUE TITLE
"SPAM"

### ISSUE THREAD

**Issue by ghost** [Lebyy/SmartChatBot#11]

**Comment by ririko5834** [comment]
I have same problem

**Comment by ririko5834** [comment]
I get `{"message":"\"The chatbot endpoint is currently having issues! There was an error generating an response, our team is working on a fix and will be resolved at the earliest possible! Thank you so much for using the API","error":true}` now @Lebyy

**Comment by JoeyRainbowZ** [comment]
Ye me too

**Comment by Lebyy** [comment]
Fixed!

**Comment by ririko5834** [comment]
{"statusCode":500,"code":"ERR_NON_2XX_3XX_RESPONSE","error":"Internal Server Error","message":"Response code 502 (Bad Gateway)"} @Lebyy
